Setup Github action to run benchmarks and publish results
scikit-learn-inria-fondation/pdist_aggregation pull request #8
Opened 2021-05-14 11:34 UTC by mbatoul

2021-05-15 19:19 UTC, jjerphan commented
Is this branch ready for review, @mbatoul?

2021-05-15 19:20 UTC, mbatoul commented
If you're happy with the [published results](https://scikit-learn-inria-fondation.github.io/pdist_aggregation/), it's ready for review yes!

2021-05-15 20:11 UTC, jjerphan requested changes
Thanks @mbatoul!

I've added https://github.com/scikit-learn-inria-fondation/pdist_aggregation/pull/8/commits/bb3857641b486316ed80a5ee123e417823b1205f for small improvements on the notebook as well as a suggestion to fix threads over-subscription which might be present.

2021-05-15 20:11 UTC, jjerphan commented on .github/workflows/benchmark.yml
> +          export OPENBLAS_NUM_THREADS=$NUM_CORES
We need to avoid threads over-subscription when using BLAS/MKL within code parallelised by OpenMP, which must happen here.

I think of adding this in another PR improving benchmarks which would introduce `threadpoolctl` to do so. For the time being we can solve it setting the environment variables accordingly.
```suggestion
          export OMP_NUM_THREADS=$NUM_CORES
          # Avoid threads over-subscription in parallel implementation 
          # TODO: remove once threadpoolctl is set.
          export MKL_NUM_THREADS=1
          export OPENBLAS_NUM_THREADS=1
```

2021-05-16 11:16 UTC, merged

2021-05-16 11:17 UTC, jjerphan commented
Thanks @mbatoul.